name: Release
on:
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - uses: microsoft/setup-msbuild@v1
                
 #       - name: Setup engine
 #           run: .\SetupEngine.bat
 #       - name: Package game
            #run: .\PackageGame.bat